### ISSUE TITLE
setup package build and testing framework for pdg-staging

### ISSUE THREAD

**Issue by mbjones** [PermafrostDiscoveryGateway/viz-staging#37]
In discussing the need to better package testing, we discussed the need to run unit and integration tests for all packages. This issue is to set up `poetry` package metadata and `pytest` as a testing framework and create example tests to be expanded.

- [x] Configure poetry
- [x] Configure pytest

**Comment by mbjones** [comment]
Started implementation of this build and test framework in branch https://github.com/PermafrostDiscoveryGateway/viz-staging/tree/feature-37-poetry-build . This provides a pyproject.toml file and a basic pytest setup with tests in the `tests` directory. Example tests are currently just no-ops, and this is meant to be a starting point for a discussion on package build and setup for testing. 

To build the package, run `poetry build`, to install it run `poetry install`. To run the tests, run `pytest` from the root of the package directory. 

@julietcohen @westminsterabi feedback appreciated, and let's discuss if this would help build out a better package test suite

**Comment by mbjones** [comment]
Found an issue that `pydantic` was a required package but was not listed in the package dependencies. Fixed in sha 50449ab3 and pushed to `develop`.

**Comment by rushirajnenuji** [comment]
Looks like this [PR](https://github.com/PermafrostDiscoveryGateway/viz-staging/pull/38) has been merged with develop and added to main with the [0.9.2 release](https://github.com/PermafrostDiscoveryGateway/viz-staging/releases/tag/v0.9.2), so closing this out.
